### ISSUE TITLE
more clear error from server (and handled by client) if money has already been spent

### ISSUE THREAD

**Issue by gWOLF3** [kanzure/webcash#1]
```
🧟  webcash $ python3 walletclient.py insert e10000:secret:70eb0ee4a2c8e0265505311f49ba2f5e3bb14097518ff2ba5e4a5c6acad4c919
Done! Saved e10000 in the wallet, with the memo:

🧟  webcash $ python3 walletclient.py insert 
e10000:secret:70eb0ee4a2c8e0265505311f49ba2f5e3bb14097518ff2ba5e4a5c6acad4c919
Traceback (most recent call last):
  File "walletclient.py", line 278, in <module>
    cli()
  File "/Users/gWOLF3/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gWOLF3/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/gWOLF3/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gWOLF3/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gWOLF3/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "walletclient.py", line 147, in insert
    raise Exception("Something went wrong on the server: ", response.content)
Exception: ('Something went wrong on the server: ', b'<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>')
```

**Comment by kanzure** [comment]
Fixed by a recent update. Source of the problem was that the server's error handling was misconfigured and raising an exception instead of returning an error.
